name: $(Year:yy).$(DayOfYear).vscode-open-faas-explorer.$(Build.SourceBranchName).$(Rev:rr)
trigger:
- master
pool:
  vmImage: 'windows-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- bash: |
    npm install -g vsce
  displayName: Install VSCE packager
- bash: |
    npm install
  displayName: Install Node.js dependencies
- task: Npm@1
  inputs:
    command: custom
    customCommand: test 
  displayName: Run unit tests
  continueOnError: true
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/test/test-results.xml'
- bash: |
    curl -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-windows.zip
  displayName: Download Sonar Scanner
- task: ExtractFiles@1
  inputs: 
   archiveFilePatterns: sonar-scanner*.zip
   destinationFolder: .
- powershell: |
    sonar-scanner.bat -D"sonar.projectKey=efog_vscode-open-faas-explorer" -D"sonar.organization=efog-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=1f99b9fcb97e50282539815b793999467b65c0f0"
  displayName: Run Sonar Scanner
- bash: |
    vsce package -o open-faas-explorer.vsix
  displayName: Package VSIX
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: open-faas-explorer-vsix
    PathtoPublish: open-faas-explorer.vsix